### ISSUE TITLE
Confirm Button should be green

### ISSUE THREAD

**Issue by oakgary** [speee/jsx-slack#114]
```
<Confirm title="Commit your action" confirm="Yes, please" deny="Cancel">
  <b>Are you sure?</b> Please confirm your action again.
</Confirm>
```
^ Inside a RadioButtonGroup confirm leads to:

![image](https://user-images.githubusercontent.com/13177748/74614280-ec12b200-5116-11ea-85f7-88c85cf6b83c.png)

I propose the button should be green by default or adjustable.

**Comment by yhatt** [comment]
We are *NOT* Slack so cannot answer about the feature not supported in Slack Block Kit. Please ask and feedback to Slack.

Close it because we have to focus tracking the issue related to jsx-slack.

**Comment by yhatt** [comment]
I don't know this issue had become a starting point, but Now [Slack has made adjustable the style for the confirm button through `style` field](https://api.slack.com/reference/block-kit/composition-objects#confirm).

I'll work to add `style` prop to `<Confirm>` component.
