### ISSUE TITLE
multiple text and Select on the same line

### ISSUE THREAD

**Issue by blademckain** [speee/jsx-slack#116]
It is possible create a template with multiple text and Select option on the same line?
How?

**Comment by yhatt** [comment]
Just use `<Select>` in `<Section>` layout block. Does this satisfy your requirements?

```jsx
<Blocks>
  <Section>
    text with<br />
    multiple lines
    <Select>
      <Option value="foo">foo</Option>
      <Option value="foo">bar</Option>
    </Select>
  </Section>
</Blocks>
```

[<img width="559" src="https://user-images.githubusercontent.com/3993388/75333834-2d028780-58ca-11ea-9ef8-b3832f9f59d3.png" />](https://api.slack.com/tools/block-kit-builder?mode=message&blocks=%5B%7B%22type%22%3A%22section%22%2C%22text%22%3A%7B%22type%22%3A%22mrkdwn%22%2C%22text%22%3A%22text%20with%5Cnmultiple%20lines%22%2C%22verbatim%22%3Atrue%7D%2C%22accessory%22%3A%7B%22type%22%3A%22static_select%22%2C%22options%22%3A%5B%7B%22value%22%3A%22foo%22%2C%22text%22%3A%7B%22type%22%3A%22plain_text%22%2C%22text%22%3A%22foo%22%2C%22emoji%22%3Atrue%7D%7D%2C%7B%22value%22%3A%22foo%22%2C%22text%22%3A%7B%22type%22%3A%22plain_text%22%2C%22text%22%3A%22bar%22%2C%22emoji%22%3Atrue%7D%7D%5D%7D%7D%5D)
