### ISSUE TITLE
Question: How to keep linebreaks from variable

### ISSUE THREAD

**Issue by oakgary** [speee/jsx-slack#169]
Hello yhatt. 
This is a question and not an issue. I hope it is ok for me to ask here.

I am trying something like:
```
...
<Section>
  <b>{headline}</b>
  <br />
  {description}
</Section>
...
```
where description is a string like `This is my description.\nWith linebreaks.\nTest`

When i try to display it in slack the linebreaks in the description get lost somewhere in the parsing.
Can you tell me how to keep the linebreaks to be also displayed in slack?

**Comment by oakgary** [comment]
It does work like this:
```
{description.split('\n').map(line => (
  <Fragment>
    {line} <br />
  </Fragment>
))}
```

But I am wondering if it is the recommended solution.

**Comment by yhatt** [comment]
jsx-slack always ignores line breaks while parsing JSX, as same as React. So the recommended solution is also as same as a way to React: [React Newline to break (nl2br)](https://medium.com/@kevinsimper/react-newline-to-break-nl2br-a1c240ba746)

Use your way with confidence!
