### ISSUE TITLE
Support for Dispatch Action Config for Plain Text Input

### ISSUE THREAD

**Issue by raycharius** [speee/jsx-slack#204]
As seen here: https://api.slack.com/reference/block-kit/block-elements#input

**Comment by yhatt** [comment]
Thanks to mention for lost part of `dispatchAction`. In jsx-slack, it would become to the extra option of `dispatchAction` prop: `<Input dispatchAction={["onEnterPressed", "onCharacterEntered"]}>`.

**Comment by yhatt** [comment]
Done in #205. The configurable `dispatchAction` prop is going to come in the next release.

https://speee-jsx-slack.netlify.app/#jsx:eJyz8cjPTbXjUlCw8cwrKC1RyElMSs2xVQpOTSxKzlBSSMksLkgsSc5wTC7JzM-zVcrPc80rSS0KKEotLk5NUVLQt-Oy0QcbAQCB_Rha

```jsx
<Home>
  <Input label="Search" dispatchAction="onEnterPressed" />
</Home>
```

```json
{
  "type": "home",
  "blocks": [
    {
      "type": "input",
      "label": {
        "type": "plain_text",
        "text": "Search",
        "emoji": true
      },
      "optional": true,
      "dispatch_action": true,
      "element": {
        "type": "plain_text_input",
        "dispatch_action_config": {
          "trigger_actions_on": [
            "on_enter_pressed"
          ]
        }
      }
    }
  ]
}
```
