### ISSUE TITLE
Integration with htm

### ISSUE THREAD

**Issue by mwildehahn** [speee/jsx-slack#6]
I haven't looked into this so not sure if it is possible, but it would be cool to integrate with: https://github.com/developit/htm so devs didn't have to have a transpiler.

**Comment by yhatt** [comment]
Yeah, it's so cool. Currently, @speee-js/jsx-slack can use via htm such as following:

```jsx
import JSXSlack, { Block, Section } from '@speee-js/jsx-slack'
import { bind } from 'htm'

const slack = (...args) => JSXSlack(bind(JSXSlack.h)(...args))
const name = 'htm'

console.log(slack`
  <${Block}>
    <${Section}>
      Hello, <b>${name}!</b>
    <//>
  <//>
`)
```

```
[
  {
    "type": "section",
    "text": {
      "text": "Hello, *htm!*",
      "type": "mrkdwn",
      "verbatim": true
    }
  }
]
```

But it has a bit counterintuitive interpolation for using Block component. (`<${Block}><//>`) Preparing tagged template that has already supported Block components is the best way to use jsx-slack without transpiler.

**Comment by yhatt** [comment]
We've merged htm integration via `jsxslack` tagged template literal. (#7) We are going to bump up version if no problems.
