### ISSUE TITLE
Allow `verbatim={boolean}` parameter 

### ISSUE THREAD

**Issue by luke-polly** [speee/jsx-slack#73]
For text objects, Slack allows a parameter `verbatim` to be passed, allowing some elements to be parsed by slack, without needing specific mrkdwn syntax (e.g. channels, users, urls). From Slack's doc on text object: https://api.slack.com/reference/block-kit/composition-objects#text

When set to false (as is default) URLs will be auto-converted into links, conversation names will be link-ified, and certain mentions will be automatically parsed. Using a value of true will skip any preprocessing of this nature, although you can still include manual parsing strings. This field is only usable when typeis mrkdwn.

It would be ideal to be able to use this attribute for components that support a text object (e.g. Section, Context, Fields (and pass them down to child elements). A specific use case where this would be ideal is rendering dynamic input in slack. If the dynamic content contains a URL, passing the text into a `jsx-slack` component such as a `<Button>` means you would first have to search for url's and wrap them with `<a>...</a>` to get them to render as links in Slack. Ideally you could opt into the `verbatim` parameter to simply pass the raw text to Slack to parse

**Comment by yhatt** [comment]
The reason why we don't support `verbatim` option is that Slack does not recommend to use this option (https://api.slack.com/messaging/composing/formatting#why_you_should_consider_disabling_automatic_parsing).

`verbatim` would effect to not only URL links but user mentions, and it may break references by changing a name. jsx-slack is not using `verbatim` to avoid some troubles. For wrapping URL by `<a>`, I think creating the custom component (similar to [react-linkify](https://github.com/tasti/react-linkify/)) is better.

If user still want `verbatim`, we should consider JSX interface for this option: Add `verbatim` prop to layout blocks, or provide `<Verbatim>` component that can use in HTML context.

**Comment by javaPhil** [comment]
Hey @yhatt. I have some use cases where I need to use `verbatim=false`. I would like to write a pull request to solve this issue. How should I proceed?

**Comment by yhatt** [comment]
@javaPhil We are welcome to new pull request anytime, but let us consider about the interface and usage to support `verbatim=false` on jsx-slack.

I suppose you should get start working easily if there was well-discussed steady specification.

---

## Interface

If we supported to disable `verbatim` for *([not recommended](https://api.slack.com/messaging/composing/formatting#why_you_should_consider_disabling_automatic_parsing))* automatic parsing, I think that creating new component usable in the context of HTML style formatting to allow controlling verbatim flag is better than adding `verbatim={false}` prop to existed components.

The field that can control `verbatim` flag may be available in new somewhere by the future updates by Slack, so adding built-in support in jsx-slack would be better than adding props to the specific components one by one.

## Component ideas

There are 2 ideas of the new component to disable `verbatim` flag. We have to discuss and choose either one.

### `<Verbatim>` component

`<Verbatim>` component will simply work to resolve this issue.

jsx-slack is enabling `verbatim` by default, but user can disable it by wrapping the content in `<Verbatim disabled>`.

```jsx
<Blocks>
  <Section>
    <Verbatim disabled={true}>
      <i>@channel</i> Hi!
    </Verbatim>
  </Section>
</Blocks>
```

### `<Mrkdwn>` component (Composition object)

`<Mrkdwn>` component corresponds with [Slack's text composition object with `mrkdwn` type](https://api.slack.com/reference/block-kit/composition-objects#text). It may be intuitive for user familiar with Slack API.

```jsx
<Blocks>
  <Section>
    <Mrkdwn verbatim={false}>
      <i>@channel</i> Hi!
    </Mrkdwn>
  </Section>
</Blocks>
```

## Specifications

### [`<Section>`](https://github.com/speee/jsx-slack/blob/master/docs/layout-blocks.md#section) and [`<Confirm>`](https://github.com/speee/jsx-slack/blob/master/docs/block-elements.md#confirm)

Both of components must be *a only child of the parent component*.

```jsx
// Bad
<Blocks>
  <Section>
    <Verbatim disabled={true}>
      <i>@channel</i>
    </Verbatim>
    Hi!
  </Section>
<Blocks>
```

```jsx
// Bad
<Blocks>
  <Section>
    <Mrkdwn verbatim={false}>
      <i>@channel</i>
    </Mrkdwn>
    Hi!
  </Section>
<Blocks>
```

### [`<Context>`](https://github.com/speee/jsx-slack/blob/master/docs/layout-blocks.md#context)

A specification would be complicated for supporting `<Context>` block. It allows mixed contents consisted of text and image to support natural templating

```jsx
<Blocks>
  <Context>
    <Image src="https://github.com/yhatt.png" alt="yhatt" />
    Supporting <code>context</code> block would be hard!
    <Verbatim disabled={true}>
      <i>@here</i>
    </Verbatim>
    :dizzy_face: 
  </Context>
</Blocks>
```

This example should be converted as following:

```json
[
  {
    "type": "context",
    "elements": [
      {
        "type": "image",
        "image_url": "https://github.com/yhatt.png",
        "alt_text": "yhatt"
      },
      {
        "type": "mrkdwn",
        "text": "Supporting `context` block would be hard!",
        "verbatim": true
      },
      {
        "type": "mrkdwn",
        "text": "_@here_",
        "verbatim": false
      },
      {
        "type": "mrkdwn",
        "text": ":dizzy_face:",
        "verbatim": true
      },
    ]
  }
]
```

An added component to disable verbatim flag should behave like [`<span>` intrinsic HTML](https://github.com/speee/jsx-slack/pull/31) in `<Context>` block.

As shown in this structure, `<Image>` and `<img>` cannot use in added component.


```jsx
// Bad
<Blocks>
  <Context>
    <Mrkdwn verbatim={false}>
      <img src="https://github.com/yhatt.png" alt="yhatt" />
      Bad
    </Mrkdwn>
  </Context>
</Blocks>
```

---

At the moment, I have no time to take care with considering many concerns in above, *for supporting deprecated feature in Slack*. I hope for leading by community.

**Comment by yhatt** [comment]
We've received a pull request so I have to share our deep thinking about `<Mrkdwn>` component for Slack's text composition object.

Current jsx-slack can think that the surface of HTML-like formatting is wrapped implicitly in `<Mrkdwn verbatim={true}>`.

```jsx
<Blocks>
  <Section>Hello!</Section>
</Blocks>
```

It means the same as below:

```jsx
<Blocks>
  <Section>
    <Mrkdwn verbatim={true}>Hello!</Mrkdwn>
  </Section>
</Blocks>
```

An explicitly declared `<Mrkdwn>` component means using text composition object with customized attributes.

```jsx
<Blocks>
  <Section>
    <Mrkdwn verbatim={false}>Hello!</Mrkdwn>
  </Section>
</Blocks>
```

The JSX structure becomes similar as the original JSON structure defined by Slack. For example, below block elements are valid all.

```jsx
<Blocks>
  <Section>
    <Mrkdwn verbatim={false}>
      Hello!
    </Mrkdwn>
  </Section>
  <Section>
    <Field>
      <Mrkdwn verbatim={false}>
        Hello!
      </Mrkdwn>
    </Field>
  </Section>
  <Context>
    <Mrkdwn verbatim={false}>
      Hello!
    </Mrkdwn>
  </Context>
  <Actions>
    <Button confirm={
      <Confirm title="Commit your action" confirm="Yes, please" deny="Cancel">
        <Mrkdwn verbatim={false}>
          Are you sure?
        </Mrkdwn>
      </Confirm>
    }>
      Button
    </Button>
  </Actions>
</Blocks>
```

And the outputted JSON is this:

```json
[
  {
    "type": "section",
    "text": {
      "text": "Hello!",
      "type": "mrkdwn",
      "verbatim": false
    }
  },
  {
    "type": "section",
    "fields": [
      {
        "type": "mrkdwn",
        "text": "Hello!",
        "verbatim": false
      }
    ]
  },
  {
    "type": "context",
    "elements": [
      {
        "type": "mrkdwn",
        "text": "Hello!",
        "verbatim": false
      }
    ]
  },
  {
    "type": "actions",
    "elements": [
      {
        "type": "button",
        "text": {
          "type": "plain_text",
          "text": "Button",
          "emoji": true
        },
        "confirm": {
          "title": {
            "type": "plain_text",
            "text": "Commit your action",
            "emoji": true
          },
          "text": {
            "type": "mrkdwn",
            "text": "Are you sure?",
            "verbatim": false
          },
          "confirm": {
            "type": "plain_text",
            "text": "Yes, please",
            "emoji": true
          },
          "deny": {
            "type": "plain_text",
            "text": "Cancel",
            "emoji": true
          }
        }
      }
    ]
  }
]
```

**Comment by yhatt** [comment]
#97 was merged but `<Mrkdwn>` for `<Field>` component would not be worked. Re-open issue.
